### ISSUE TITLE
"Hi, what drink do you prefer?" in a loop..

### ISSUE THREAD

**Issue by mkeval** [dgtony/afg#6]
"Hi, what drink do you prefer?" is asked again and again after adding 
init:
    reprompt:
      - "Hi, what drink do you prefer?"

Please help to resolve.

**Comment by dgtony** [comment]
You just can't move out of `init` state, invoking special intent instead of `launched` one.
The same issue [here](https://github.com/dgtony/afg/issues/5).

**Comment by mkeval** [comment]
Okay. Got it. Issue solve.! Thanks a lot.
