### ISSUE TITLE
Installation fails due to conflicting pyyaml version

### ISSUE THREAD

**Issue by NeolithEra** [dgtony/afg#9]
Hi, users are unable to run **_afg_** due to dependency conflict with _**pyyaml**_ package. As shown in the following full dependency graph of _**afg**_, **_afg_** requires **_pyyaml *_**，while **_flask-ask_** requires _**pyyaml ==3.12**_.

According to pip’s _“first found wins”_ installation strategy, _**pyyaml 5.1.2**_ is the actually installed version. However, _**pyyaml 5.1.2**_ does not satisfy _**==3.12**_. 

### Dependency tree-----------
```
afg - 0.2
| +- flask-ask(install version:0.9.8 version range:*)
| | +- aniso8601(install version:1.2.0 version range:==1.2.0)
| | | +- python-dateutil(install version:2.8.1 version range:*)
| | +- flask(install version:0.12.1 version range:==0.12.1)
| | | +- click(install version:7.0 version range:>=2.0)
| | | +- itsdangerous(install version:1.1.0 version range:>=0.21)
| | | +- jinja2(install version:2.10.3 version range:>=2.4)
| | | | +- markupsafe(install version:1.1.1 version range:>=0.23)
| | | +- werkzeug(install version:0.16.0 version range:>=0.7)
| | +- pyopenssl(install version:17.0.0 version range:==17.0.0)
| | | +- cryptography(install version:2.8 version range:>=1.7)
| | | +- six(install version:1.11.0 version range:>=1.5.2)
| | +- pyyaml(install version:3.12 version range:==3.12)
| | +- six(install version:1.11.0 version range:==1.11.0)
| +- fysom(install version:2.1.5 version range:*)
| +- pyyaml(install version:5.1.2 version range:*)
| +- wrapt(install version:1.11.2 version range:*)
```

Thanks for your help.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Solution

1.	Fix your direct dependency to be **_pyyaml==3.12_**. I have checked this revision will not affect your downstream projects now.
2.	Ask your upstream project **_bioc_** to loose the version range of **_pyyaml_**.

Which solution do you prefer, 1 or 2?
Please let me know your choice. I can submit a PR to solve this issue.

**Comment by dgtony** [comment]
Hi!
Assuming this project entirely depends on **flask-ask**, it is pretty reasonable to restrict common dependency version locally. So first solution looks ok.
